name: CI-Deployment

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ feature ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: feature
        # Fetch all history commit
        fetch-depth: 0
    - uses: actions/setup-node@v1
      with:
        node-version: '16.6.0'

    - name: Install SFDX & SFDX Git Delta
      run: |
        wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
        sudo mkdir ~/sfdx-cli
        sudo tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx-cli --strip-components 1
        export PATH=$PATH:~/sfdx-cli/bin
        echo "~/sfdx-cli/bin" >> $GITHUB_PATH
        sudo chmod -R 777 ~/sfdx-cli
        sfdx --version

    - name: Generate package.xml
      run: |
        #Generate package.xml between the current branch &
        mkdir changed-sources
        sfdx sgd:source:delta --to "HEAD" --from "HEAD^" --output changed-sources/ --generate-delta --source force-app/ 

    - name: Authentication
      run: |
        openssl enc -nosalt -aes-256-cbc -d -in assets/server.key.enc -out server.key -base64 -K ${{secrets.DECRYPTION_KEY}} -iv ${{secrets.DECRYPTION_IV}}
        sfdx auth:jwt:grant --clientid ${{ secrets.CONSUMER_KEY }} --jwtkeyfile server.key --username ${{ secrets.USERNAME }} --setdefaultdevhubusername --setalias prod

    - name: Deployement
      run: |
        sfdx force:source:deploy -p changed-sources/force-app -l RunLocalTests -u prod